# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2.1"

services:
  validator:
    image: hyperledger/sawtooth-validator:1.1
    container_name: sabre-validator
    volumes:
      - .:/project
    expose:
      - 9704
    ports:
      - "9704:9704"
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen && \
        mkdir -p /project/keys && \
        cp /root/.sawtooth/keys/* /project/keys &&
        sawset genesis  -k /etc/sawtooth/keys/validator.priv && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.swa.administrators=$$(cat project/keys/root.pub) \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:9705 \
          --bind component:tcp://eth0:9704 \
          --bind network:tcp://eth0:9705 \
          --bind consensus:tcp://eth0:5050 \
        \""

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sabre-sawtooth-rest-api
    expose:
      - 9708
    ports:
      - "9708:9708"
    entrypoint: sawtooth-rest-api --connect tcp://validator:9704 --bind rest-api:9708 -vv

  shell:
    image: hyperledger/sawtooth-shell:1.1
    container_name: sabre-shell
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sabre-settings-tp
    entrypoint: settings-tp -vv --connect tcp://validator:9704

  devmode-rust:
    image: hyperledger/sawtooth-devmode-engine-rust:1.1
    container_name: sawtooth-devmode-engine-rust
    depends_on:
      - validator
    command: |
        devmode-engine-rust -v --connect tcp://validator:5050
    stop_signal: SIGKILL

  sabre-tp:
    image: sabre-tp:${ISOLATION_ID}
    container_name: sabre-tp
    entrypoint: "bash -c \"\
        cd /project/tp/ && \
        cargo build && \
        sawtooth-sabre -vv -C tcp://validator:9704 \
        \""
    volumes:
      - .:/project
    build:
      context: tp

  sabre-cli:
    image: sabre-cli:${ISOLATION_ID}
    container_name: sabre-cli
    volumes:
      - .:/project
      - ./keys:/root/.sawtooth/keys
    entrypoint: "bash -c \"\
      cargo build && \
      tail -f /dev/null \
      \""
    build:
      context: cli
